import Link from "next/link"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function About() {
  return (
    <div>
    <h1 className="">Сторінка про нас</h1>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cumque ullam provident, perspiciatis reiciendis vel dolorum quidem ipsam animi maxime facilis explicabo tempora numquam laboriosam labore magnam saepe, dolorem veniam? Quae?
      </p>
    </div>
  )
}

